package lt.dm3.jquickcheck.api;

import java.lang.reflect.Type;

/**
 * Resolves the type of the values generated by a generator from the given context.
 * 
 * @author dm3
 * 
 * @param <T>
 */
public interface GeneratorTypeResolver<T> {

    /**
     * Does not throw exceptions!
     * 
     * @param context
     *            any object
     * @return the Type of the values to be generated by a generator or null if the type could not be determined
     */
    Type resolveFrom(T context);

}
